### ISSUE TITLE
Framework bonus point gameplay mechanic

### ISSUE THREAD

**Issue by bennett000** [rangle/block-drop#62]
The idea behind this card is to work the front-end framework in use into the front end gameplay.

- [ ] Add a framework mode flag to the engine
- [ ] Add an input to the engine that sets the framework mode
- [ ] Add a ruleset that gives point bonuses when they align with the framework toggle

This story needs #54 to happen first

**Comment by smithad15** [comment]
Just adding some user-facing AC below:

- When a player clears a section of blocks that have the same colour as the currently active framework, they should be awarded 2x points
